host: "0.0.0.0"
port: "8080"
log_level: "debug"
version: "0.1.0"

postgres:
  database: "meemo_db"
  user: "meemo_user"
  password: "meemo_password"
  host: "postgres"
  port: "5432"
  retries: 5
  pool_size: 10
  ssl_mode: "disable"

s3:
  aws_region: "us-east-1"
  aws_endpoint: "http://minio:9000"  # Для MinIO/LocalStack. Для Ceph используйте порт 8000. Оставьте пустым для AWS S3
  aws_access_key_id: "minioadmin"
  aws_secret_access_key: "minioadmin"
  aws_bucket_name: "meemo-bucket"
  force_path_style: true  # true для MinIO/Ceph/LocalStack, false для AWS S3

s3_bucket_name: "meemo-bucket"

