host: "localhost"
port: 8085
s3_bucket_name: "bucket"

postgres:
  database: "postgres"
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: 5433
  retries: 5
  pool_size: 20
  ssl_mode: "disable"

s3:
  minio_endpoint: "localhost:9000"
  minio_access_key_id: "your_access_key"
  minio_secret_key: "your_secret_key"
  minio_use_ssl: false
  minio_bucket_name: "bucket"