name: backend-ci-dev

on:
  pull_request:
    branches: [ "prod" ]


jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: Login to Yandex Container Registry
        run: |
          echo "${{ secrets.YC_TOKEN }}" | docker login \
            --username oauth \
            --password-stdin \
            cr.yandex/${{ secrets.YC_REGISTRY_ID }}

      - name: Build and push image
        run: |
          IMAGE=cr.yandex/${{ secrets.YC_REGISTRY_ID }}/dev/backend:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
